# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d')),
                ('level', models.CharField(choices=[(b'N1', b'N1'), (b'N2', b'N2'), (b'N3', b'N3'), (b'N4', b'N4'), (b'N5', b'N5'), (b'NO', b'NO')], max_length=2, verbose_name=b'\xe9\x9a\xbe\xe5\xba\xa6')),
            ],
        ),
    ]
